"""Output adapter: IIFE → ESM / Web Component.

把 IIFE 形态的组件库源码转换为 ESM 或 Web Component 形态。
agent 产出 IIFE 源码后，用此模块生成其他输出形态。

业务逻辑层：本模块提供 ``extract_iife_core`` / ``to_esm`` / ``to_web_component``
等函数，不含 CLI 入口。CLI 入口见 ``ui_dismantler.cli.adapt_output``。

原理：
  IIFE 源码结构为 (function(global){...function Lib(root,options){...}...global.Lib=API})(window)
  适配器：
  - ESM：去掉 IIFE 包裹，把 function Lib 提取为模块内函数，export mount/create
  - Web Component：把 Lib 包成 customElements.define('tag-name', class extends HTMLElement)
    connectedCallback 里调 mount(this, parsed options)
"""
from __future__ import annotations
import re
from pathlib import Path


def extract_iife_core(src: str) -> tuple[str, str, str]:
    """从 IIFE 源码提取核心部分。

    返回 (preamble, body, api_name)：
    - preamble: IIFE 开头 (function(global){"use strict"; ... 到 function Lib 之前)
    - body: function Lib(root,options){...} 到 return {...} 之后的 }
    - api_name: 暴露的全局名（如 KzkAbout）
    """
    # 找 IIFE 包裹
    m = re.search(r'\(function\s*\(\s*global\s*\)\s*\{("use strict";)?', src)
    if not m:
        raise ValueError("未找到 IIFE 包裹 (function(global){...})")
    use_strict = m.group(1) or ""
    # 找 API 名
    api_m = re.search(r'global\.(\w+)\s*=\s*API\s*;', src)
    if not api_m:
        raise ValueError("未找到 global.XXX = API 暴露语句")
    api_name = api_m.group(1)
    # 找 function Lib( 构造函数
    lib_start = re.search(r'function\s+(\w+)\s*\(\s*root\s*,\s*options\s*\)\s*\{', src)
    if not lib_start:
        raise ValueError("未找到 function Lib(root, options) 构造函数")
    lib_name = lib_start.group(1)
    # preamble：IIFE 开头到 function Lib 之前
    preamble = src[m.end():lib_start.start()]
    # body：function Lib 到最后的 return {...} 之后的闭合 }
    # 找 var API = { ... }; 之前的部分是 body
    api_var_start = src.find('var API = {', lib_start.start())
    if api_var_start < 0:
        raise ValueError("未找到 var API = {")
    body = src[lib_start.start():api_var_start]
    return preamble, body, api_name, lib_name, use_strict


def to_esm(src: str) -> str:
    """转换为 ESM/UMD 形态：去掉 IIFE 包裹，暴露 mount/create 到全局。

    构造函数改名为 _LibCtor 避免与全局 API 名冲突（jsdom 同一作用域覆盖）。
    """
    preamble, body, api_name, lib_name, use_strict = extract_iife_core(src)
    body_renamed = body.replace(f"function {lib_name}(", "function _LibCtor(")
    esm = f"""// ESM/UMD output (generated by adapt_output.py from IIFE)
"use strict";
{preamble}
{body_renamed}

function mount(container, options) {{
  if (!container) throw new Error("{api_name}.mount: container is required");
  return new _LibCtor(container, options);
}}

function create(options) {{
  const c = document.createElement("div");
  return new _LibCtor(c, options);
}}

if (typeof window !== "undefined") {{
  window.{api_name} = {{ mount: mount, create: create }};
}}
"""
    return esm

def to_web_component(src: str, tag_name: str) -> str:
    """转换为 Web Component 形态：customElements.define(tag-name, class)。"""
    preamble, body, api_name, lib_name, use_strict = extract_iife_core(src)
    # 把 function Lib(root, options) 改成 function Lib(root, options)
    # Web Component：class extends HTMLElement，connectedCallback 调 mount
    # options 从 data-* 属性或 <script type="application/json"> 子元素解析
    wc = f"""// Web Component 输出（由 adapt_output.py 从 IIFE 生成）
// 用法：<{tag_name} data-options='{{"hero":{{...}}}}'></{tag_name}>
//   或 <{tag_name}><script type="application/json">{{...}}</script></{tag_name}>
{use_strict}
{preamble}
{body}

class {lib_name}Element extends HTMLElement {{
  constructor() {{
    super();
    this._instance = null;
  }}

  connectedCallback() {{
    if (this._instance) return;  // 避免重复挂载
    const options = this._parseOptions();
    this._instance = new {lib_name}(this, options);
  }}

  disconnectedCallback() {{
    this._instance = null;
    this.innerHTML = "";
  }}

  _parseOptions() {{
    // 优先：<script type="application/json"> 子元素
    const script = this.querySelector('script[type="application/json"]');
    if (script) {{
      try {{ return JSON.parse(script.textContent); }} catch (e) {{ console.warn("{tag_name}: JSON 解析失败", e); }}
    }}
    // 次选：data-options 属性
    const attr = this.getAttribute("data-options");
    if (attr) {{
      try {{ return JSON.parse(attr); }} catch (e) {{ console.warn("{tag_name}: data-options 解析失败", e); }}
    }}
    return {{}};
  }}

  // 暴露实例方法
  get instance() {{ return this._instance; }}
}}

if (typeof customElements !== "undefined" && !customElements.get("{tag_name}")) {{
  customElements.define("{tag_name}", {lib_name}Element);
  // upgrade 已存在的元素（元素在 define 前已插入 DOM 的情况）
  // upgrade 不重新触发 connectedCallback，需手动调用
  document.querySelectorAll("{tag_name}").forEach(function(el) {{
    if (customElements.upgrade) customElements.upgrade(el);
    if (el.connectedCallback && !el._instance) el.connectedCallback();
  }});
}}

export {{ {lib_name}Element as {lib_name}Component }};
export default {{ }};
"""
    return wc
