// Generated by ui-dismantler route-shell generator. Review before production use.
export const routes = [
  {
    "route": "/#/dashboard",
    "pattern": "/#/dashboard",
    "patternRegex": "^/#/dashboard$",
    "entry": true,
    "final": true,
    "scenarios": [
      "unauthenticated-dashboard-guard",
      "admin-login-dashboard",
      "admin-nested-route",
      "admin-history-back",
      "admin-permission-route",
      "admin-deep-link-reload"
    ]
  },
  {
    "route": "/#/login?redirect=%2Fdashboard",
    "pattern": "/#/login?redirect=%2Fdashboard",
    "patternRegex": "^/#/login?redirect=%2Fdashboard$",
    "entry": false,
    "final": true,
    "scenarios": [
      "unauthenticated-dashboard-guard"
    ]
  },
  {
    "route": "/#/login",
    "pattern": "/#/login",
    "patternRegex": "^/#/login$",
    "entry": true,
    "final": false,
    "scenarios": [
      "admin-login-dashboard",
      "admin-nested-route",
      "admin-history-back",
      "admin-permission-route",
      "admin-deep-link-reload"
    ]
  },
  {
    "route": "/#/nested/menu1/menu1-1",
    "pattern": "/#/nested/menu1/menu1-1",
    "patternRegex": "^/#/nested/menu1/menu1-1$",
    "entry": false,
    "final": true,
    "scenarios": [
      "admin-nested-route"
    ]
  },
  {
    "route": "/#/documentation/index",
    "pattern": "/#/documentation/index",
    "patternRegex": "^/#/documentation/index$",
    "entry": false,
    "final": false,
    "scenarios": [
      "admin-history-back"
    ]
  },
  {
    "route": "/#/permission/directive",
    "pattern": "/#/permission/directive",
    "patternRegex": "^/#/permission/directive$",
    "entry": false,
    "final": true,
    "scenarios": [
      "admin-permission-route"
    ]
  }
];

export function matchRoute(pathname = window.location.pathname + window.location.search + window.location.hash) {
  return routes.find((route) => new RegExp(route.patternRegex).test(pathname)) ?? null;
}
