import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { performance } from "node:perf_hooks";
import type { SpaRouteShellPlan, SpaRouteShellRouteNode, SpaRouteShellTransition } from "./spa-route-shell.js";
import type { SpaRouterContractReport } from "../evaluation/spa-router.js";

export interface GeneratedSpaRouteShellFile {
  path: string;
  content: string;
  lines: number;
}

export interface SpaRouteShellDiffMetrics {
  baselinePath: string | null;
  comparableFiles: number;
  generatedFiles: number;
  baselineFiles: number;
  generatedLines: number;
  baselineLines: number;
  changedFiles: number;
  changedLines: number;
  missingBaselineFiles: string[];
  baselineOnlyFiles: string[];
  comparable: boolean;
  responsibility?: {
    sourceFiles: string[];
    manualResponsibilityLines: number;
    generatedResponsibilityLines: number;
    matchedRoutes: string[];
    missingRoutes: string[];
    matchedGuards: string[];
    missingGuards: string[];
    matchedCapabilities: string[];
    missingCapabilities: string[];
  };
  note?: string;
}

export interface SpaRouteShellQualitySummary {
  reportPath: string | null;
  available: boolean;
  passed?: boolean;
  navigationIntegrity?: number;
  worstComputedStyle?: number;
  worstPixelDiff?: number;
  runtimeErrors?: number;
  requiredNetworkFailures?: number;
  blockingHandlesAfterClose?: number;
}

export interface GeneratedSpaRouteShellMetrics {
  schemaVersion: "1.0";
  phase: "route-shell-generation";
  deterministic: true;
  reviewRequired: true;
  generatedCode: true;
  modelCalls: 0;
  generationMs: number;
  manualEdits: number;
  manualEditedLines: number;
  repairIterations: number;
  qualityRuns: number;
  generatedFiles: Array<{ path: string; lines: number }>;
  generatedLines: number;
  diff: SpaRouteShellDiffMetrics;
  manualQuality: SpaRouteShellQualitySummary;
  generatedQuality: SpaRouteShellQualitySummary;
  qualityComparison: {
    comparable: boolean;
    passed: boolean | null;
    navigationIntegrityDelta: number | null;
    computedStyleDelta: number | null;
    pixelDiffDelta: number | null;
    detail: string;
  };
  reviewReasons: string[];
}

export interface GenerateSpaRouteShellOptions {
  baselinePath?: string;
  manualReportPath?: string;
  generatedReportPath?: string;
  generationMs?: number;
  manualEdits?: number;
  manualEditedLines?: number;
  repairIterations?: number;
}

function lines(content: string): number {
  return content === "" ? 0 : content.split("\n").length - (content.endsWith("\n") ? 1 : 0);
}

function js(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function routePatternRegex(pattern: string): string {
  const escaped = pattern.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&");
  return `^${escaped.replace(/:([A-Za-z][\w-]*)/g, "(?<$1>[^/]+)")}$`;
}

function renderRoutes(routes: SpaRouteShellRouteNode[]): string {
  const routeEntries = routes.map((route) => ({
    route: route.route,
    pattern: route.pattern,
    patternRegex: routePatternRegex(route.pattern),
    entry: route.entry,
    final: route.final,
    scenarios: route.scenarios,
  }));
  return `// Generated by ui-dismantler route-shell generator. Review before production use.\nexport const routes = ${js(routeEntries)};\n\nexport function matchRoute(pathname = window.location.pathname + window.location.search + window.location.hash) {\n  return routes.find((route) => new RegExp(route.patternRegex).test(pathname)) ?? null;\n}\n`;
}

function renderGuards(transitions: SpaRouteShellTransition[]): string {
  const guards = transitions
    .filter((transition) => transition.action === "guard-redirect")
    .map((transition) => ({ from: transition.from, to: transition.to, scenarioId: transition.scenarioId }));
  return `// Generated guard skeleton. Guard intent is observed behavior and requires human approval.\nexport const guardRedirects = ${js(guards)};\n\nexport function resolveGuard(pathname, context = {}) {\n  const guard = guardRedirects.find((candidate) => candidate.from === pathname);\n  if (!guard) return null;\n  if (typeof context.isAllowed === "function" && context.isAllowed(pathname)) return null;\n  return guard.to;\n}\n`;
}

function renderRouter(plan: SpaRouteShellPlan): string {
  const dynamicRoutes = plan.capabilities.dynamicInputRoutes;
  return `import { matchRoute } from "./routes.js";\nimport { resolveGuard } from "./guards.js";\n\n// Minimal behavior-only router shell. It intentionally does not render visual DOM.\nexport function createRouter({\n  onRoute,\n  isAllowed,\n  initialState = {},\n} = {}) {\n  const notify = () => onRoute?.(window.location.pathname + window.location.search + window.location.hash, matchRoute(), initialState);\n  const navigate = (target, state = {}) => {\n    const next = resolveGuard(target, { isAllowed });\n    const resolved = next ?? target;\n    window.history.pushState({ ...state, route: resolved }, "", resolved);\n    notify();\n    return resolved;\n  };\n  const replace = (target, state = {}) => {\n    const next = resolveGuard(target, { isAllowed });\n    const resolved = next ?? target;\n    window.history.replaceState({ ...state, route: resolved }, "", resolved);\n    notify();\n    return resolved;\n  };\n  const onPopState = () => notify();\n  window.addEventListener("popstate", onPopState);\n  notify();\n  return {\n    navigate,\n    replace,\n    back: () => window.history.back(),\n    forward: () => window.history.forward(),\n    reload: () => window.location.reload(),\n    dispose: () => window.removeEventListener("popstate", onPopState),\n    capabilities: ${js({ dynamicRoutes, historyBack: plan.capabilities.historyBack, historyForward: plan.capabilities.historyForward, reload: plan.capabilities.reload })},\n  };\n}\n`;
}

function renderFixtures(plan: SpaRouteShellPlan): string {
  const fixtures = plan.fixtureDependencies.map((fixture) => ({
    method: fixture.method,
    hostname: fixture.hostname,
    path: fixture.path,
    resourceType: fixture.resourceType,
    query: fixture.query,
    requestHeaders: fixture.requestHeaders,
    responseContentType: fixture.responseContentType,
    binary: fixture.binary,
    // Body contents are deliberately omitted from the generated skeleton.
  }));
  return `// Fixture registration skeleton. Response bodies stay in reviewed test fixtures.\nexport const fixtureDependencies = ${js(fixtures)};\n\nexport function registerFixtures(register) {\n  if (typeof register !== "function") throw new TypeError("registerFixtures requires a function");\n  for (const fixture of fixtureDependencies) register(fixture);\n  return fixtureDependencies.length;\n}\n`;
}

function renderReadme(plan: SpaRouteShellPlan): string {
  return `# Generated SPA route shell\n\nThis is a **behavior-only scaffold** generated from \`${plan.kind}\`. It is not a production application and does not generate visual DOM, CSS, or component boundaries.\n\n## Review checklist\n\n- Approve route patterns and dynamic parameter names.\n- Approve observed guard redirects before enabling them.\n- Connect \`onRoute\` to the reviewed application renderer.\n- Register fixture response bodies from the audited fixture set.\n- Run the same Semantic Gold+ and route-state visual matrix against the actual generated application.\n- Keep \`reviewRequired=true\`; this generator must not silently replace an existing route shell.\n\n## Planned routes\n\n${plan.routes.map((route) => `- \`${route.pattern}\` (${route.route})`).join("\\n")}\n`;
}

export function generateSpaRouteShellArtifact(plan: SpaRouteShellPlan, options: GenerateSpaRouteShellOptions = {}): { files: GeneratedSpaRouteShellFile[]; metrics: GeneratedSpaRouteShellMetrics } {
  const started = performanceNow();
  const files: GeneratedSpaRouteShellFile[] = [
    { path: "routes.js", content: renderRoutes(plan.routes), lines: 0 },
    { path: "guards.js", content: renderGuards(plan.transitions), lines: 0 },
    { path: "router.js", content: renderRouter(plan), lines: 0 },
    { path: "fixtures.js", content: renderFixtures(plan), lines: 0 },
    { path: "README.md", content: renderReadme(plan), lines: 0 },
  ].map((file) => ({ ...file, lines: lines(file.content) }));
  const generatedMs = options.generationMs ?? Number((performanceNow() - started).toFixed(3));
  const diff = compareSpaRouteShellFiles(files, options.baselinePath);
  const manualQuality = readQualitySummary(options.manualReportPath);
  const generatedQuality = readQualitySummary(options.generatedReportPath);
  const qualityComparison = compareQualitySummaries(manualQuality, generatedQuality);
  const metrics: GeneratedSpaRouteShellMetrics = {
    schemaVersion: "1.0", phase: "route-shell-generation", deterministic: true,
    reviewRequired: true, generatedCode: true, modelCalls: 0, generationMs: generatedMs,
    manualEdits: options.manualEdits ?? 0, manualEditedLines: options.manualEditedLines ?? 0, repairIterations: options.repairIterations ?? 0,
    qualityRuns: (manualQuality.available ? 1 : 0) + (generatedQuality.available ? 1 : 0),
    generatedFiles: files.map((file) => ({ path: file.path, lines: file.lines })),
    generatedLines: files.reduce((sum, file) => sum + file.lines, 0), diff, manualQuality, generatedQuality, qualityComparison,
    reviewReasons: [
      "the scaffold contains router/history/guard/fixture behavior only",
      "visual DOM and CSS are intentionally excluded",
      "observed redirects require human approval before production use",
      "Semantic Gold+ comparison is valid only when both report paths are supplied for the actual applications",
    ],
  };
  return { files, metrics };
}

function performanceNow(): number {
  return typeof performance !== "undefined" ? performance.now() : Date.now();
}

function readQualitySummary(reportPath: string | undefined): SpaRouteShellQualitySummary {
  if (!reportPath) return { reportPath: null, available: false };
  const report = JSON.parse(readFileSync(reportPath, "utf8")) as SpaRouterContractReport;
  return {
    reportPath,
    available: true,
    passed: report.passed,
    navigationIntegrity: report.navigationIntegrity.rate,
    worstComputedStyle: report.visualMatrix?.worstComputedStyle,
    worstPixelDiff: report.visualMatrix?.worstPixelDiff,
    runtimeErrors: report.runtimeErrors,
    requiredNetworkFailures: report.requiredNetworkFailures,
    blockingHandlesAfterClose: report.telemetry.activeHandlesAfterClose.totalBlockingHandles,
  };
}

function compareQualitySummaries(manual: SpaRouteShellQualitySummary, generated: SpaRouteShellQualitySummary): GeneratedSpaRouteShellMetrics["qualityComparison"] {
  if (!manual.available || !generated.available) return {
    comparable: false, passed: null, navigationIntegrityDelta: null, computedStyleDelta: null, pixelDiffDelta: null,
    detail: "quality reports not supplied; scaffold generation does not claim visual equivalence",
  };
  const delta = (a: number | undefined, b: number | undefined): number | null => a === undefined || b === undefined ? null : Number((b - a).toFixed(6));
  return {
    comparable: true,
    passed: Boolean(manual.passed && generated.passed),
    navigationIntegrityDelta: delta(manual.navigationIntegrity, generated.navigationIntegrity),
    computedStyleDelta: delta(manual.worstComputedStyle, generated.worstComputedStyle),
    pixelDiffDelta: delta(manual.worstPixelDiff, generated.worstPixelDiff),
    detail: "comparison is a report-level summary; it does not replace the formal quality gates",
  };
}

function planRoutesFromGeneratedFiles(files: GeneratedSpaRouteShellFile[]): string[] {
  const routes = files.find((file) => file.path === "routes.js")?.content ?? "";
  return [...routes.matchAll(/\"route\":\s*\"([^\"]+)\"/g)].map((match) => match[1]);
}

function planGuardsFromGeneratedFiles(files: GeneratedSpaRouteShellFile[]): string[] {
  const guards = files.find((file) => file.path === "guards.js")?.content ?? "";
  return [...guards.matchAll(/\"from\":\s*\"([^\"]+)\"/g)].map((match) => match[1]);
}

export function compareSpaRouteShellFiles(files: GeneratedSpaRouteShellFile[], baselinePath?: string): SpaRouteShellDiffMetrics {
  const generatedByPath = new Map(files.map((file) => [file.path, file]));
  const generatedFiles = [...generatedByPath.keys()].sort();
  if (!baselinePath) return {
    baselinePath: null, comparableFiles: 0, generatedFiles: generatedFiles.length, baselineFiles: 0,
    generatedLines: files.reduce((sum, file) => sum + file.lines, 0), baselineLines: 0, changedFiles: 0, changedLines: 0,
    missingBaselineFiles: generatedFiles, baselineOnlyFiles: [], comparable: false, note: "baseline route-shell directory was not supplied",
  };
  const baselineFiles: string[] = [];
  const collect = (directory: string, prefix = ""): void => {
    for (const name of readdirSync(directory)) {
      const path = join(directory, name), relativePath = prefix ? `${prefix}/${name}` : name;
      if (statSync(path).isDirectory()) collect(path, relativePath); else baselineFiles.push(relativePath);
    }
  };
  if (existsSync(baselinePath) && statSync(baselinePath).isDirectory()) collect(baselinePath);
  else if (existsSync(baselinePath)) baselineFiles.push(relative(baselinePath, baselinePath));
  const baselineByPath = new Map<string, string>();
  for (const path of baselineFiles) {
    const absolute = existsSync(baselinePath) && statSync(baselinePath).isDirectory() ? join(baselinePath, path) : baselinePath;
    baselineByPath.set(path, readFileSync(absolute, "utf8"));
  }
  const comparable = generatedFiles.filter((path) => baselineByPath.has(path));
  const changedFiles = comparable.filter((path) => baselineByPath.get(path) !== generatedByPath.get(path)?.content);
  const changedLines = comparable.reduce((sum, path) => {
    const generated = generatedByPath.get(path)?.content.split("\n") ?? [];
    const baseline = baselineByPath.get(path)?.split("\n") ?? [];
    return sum + Math.max(generated.length, baseline.length) - 1 - generated.reduce((matches, value, index) => matches + (value === baseline[index] ? 1 : 0), 0);
  }, 0);
  const common = {
    baselinePath, generatedFiles: generatedFiles.length, baselineFiles: baselineFiles.length,
    generatedLines: files.reduce((sum, file) => sum + file.lines, 0), baselineLines: [...baselineByPath.values()].reduce((sum, content) => sum + lines(content), 0),
    missingBaselineFiles: generatedFiles.filter((path) => !baselineByPath.has(path)), baselineOnlyFiles: baselineFiles.filter((path) => !generatedByPath.has(path)),
  };
  if (comparable.length > 0) return {
    ...common, comparableFiles: comparable.length, changedFiles: changedFiles.length, changedLines: Math.max(0, changedLines), comparable: true,
    note: "line-level comparison only; review route semantics and generated behavior separately",
  };
  const appPath = baselineFiles.find((path) => path === "app.js" || path.endsWith("/app.js"));
  if (appPath) {
    const source = baselineByPath.get(appPath) ?? "";
    const sourceLines = source.split("\n");
    const generatedSource = files.map((file) => file.content).join("\n");
    const responsibilityPattern = /history\.|pushState|replaceState|popstate|navigate|location\.(pathname|search|hash)|route|guard|reload|back|forward|\/(settings|explore|library|login|search)(?:[/'"\`]|$)/i;
    const manualResponsibilityLines = sourceLines.filter((line) => responsibilityPattern.test(line)).length;
    const generatedResponsibilityLines = generatedSource.split("\n").filter((line) => responsibilityPattern.test(line)).length;
    const routeSource = (route: string): boolean => {
      if (source.includes(route)) return true;
      if (route.includes("/search/")) return /search\//.test(source);
      if (route === "/settings") return /renderSettings\s*\(/.test(source) && /return\s+renderSettings\s*\(/.test(source);
      return false;
    };
    const matchedRoutes = [...new Set(planRoutesFromGeneratedFiles(files).filter(routeSource))].sort();
    const plannedRoutes = [...new Set(planRoutesFromGeneratedFiles(files))].sort();
    const guards = [...new Set(planGuardsFromGeneratedFiles(files))].sort();
    const matchedGuards = guards.filter((guard) => source.includes(guard));
    // Reload is a browser protocol action, not necessarily an application-owned API call.
    // Compare only history behaviors that the manual route shell is expected to implement.
    const capabilities = ["historyBack", "historyForward"];
    const capabilityTokens: Record<string, RegExp> = { historyBack: /history\.back\s*\(/, historyForward: /history\.forward\s*\(/ };
    const matchedCapabilities = capabilities.filter((capability) => capabilityTokens[capability]?.test(source));
    const missingCapabilities = capabilities.filter((capability) => !matchedCapabilities.includes(capability));
    const missingRoutes = plannedRoutes.filter((route) => !matchedRoutes.includes(route));
    const missingGuards = guards.filter((guard) => !matchedGuards.includes(guard));
    const mismatch = missingRoutes.length + missingGuards.length + missingCapabilities.length;
    return {
      ...common, comparableFiles: 1, changedFiles: mismatch > 0 ? 1 : 0, changedLines: mismatch,
      comparable: true,
      responsibility: { sourceFiles: [appPath], manualResponsibilityLines, generatedResponsibilityLines, matchedRoutes, missingRoutes, matchedGuards, missingGuards, matchedCapabilities, missingCapabilities },
      note: "semantic responsibility comparison against manual app.js; not a same-file textual diff",
    };
  }
  return {
    ...common, comparableFiles: 0, changedFiles: 0, changedLines: 0, comparable: false,
    note: "baseline does not expose the same generated file boundaries",
  };
}
