// Generated by ui-dismantler route-shell generator. Review before production use.
export const routes = [
  {
    "route": "/login",
    "pattern": "/login",
    "patternRegex": "^/login$",
    "entry": true,
    "final": true,
    "scenarios": [
      "login-deep-link"
    ]
  },
  {
    "route": "/welcome",
    "pattern": "/welcome",
    "patternRegex": "^/welcome$",
    "entry": true,
    "final": true,
    "scenarios": [
      "welcome-deep-link"
    ]
  },
  {
    "route": "/nested/menu1/menu1-1",
    "pattern": "/nested/menu1/menu1-1",
    "patternRegex": "^/nested/menu1/menu1-1$",
    "entry": true,
    "final": true,
    "scenarios": [
      "nested-menu-deep-link"
    ]
  },
  {
    "route": "/echarts",
    "pattern": "/echarts",
    "patternRegex": "^/echarts$",
    "entry": true,
    "final": true,
    "scenarios": [
      "echarts-boundary-deep-link"
    ]
  }
];

export function matchRoute(pathname = window.location.pathname + window.location.search + window.location.hash) {
  return routes.find((route) => new RegExp(route.patternRegex).test(pathname)) ?? null;
}
